language: objective-c
osx_image: xcode9.4
branches:
  only:
  - master
  - develop
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
cache:
  directories:
    - $HOME/Library/Caches/org.carthage.CarthageKit/dependencies
    - Carthage
    - vendor/bundle

before_install:
  - bundle install --path vendor/bundle
  - gem install xcpretty
  - brew update
  - brew outdated carthage || brew upgrade carthage

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=CoordinatorKit.xcworkspace
    - IOS_FRAMEWORK_SCHEME="CoordinatorKit-iOS"
  matrix:
    - DESTINATION="OS=11.4,name=iPhone X"                   SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="YES"

before_script:
  - sh scripts/bootstrap

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

jobs:
  include:
    - stage: Deploy Github
      script: skip
      before_deploy:
        - carthage build --no-skip-current --cache-builds
        - carthage archive CoordinatorKit
      deploy:
        - provider: releases
          api_key:
            secure: O957kJpnkNO2ZKAhnXa0zMLd0ukc1lHuicFf8VR2IPW2HYCm0+2nZjfSiCo2wj62DydIeHTnc63zGUACHK2NkLTJvMCwElz6DahXywNJGvPgTZcbY8ME8+ZZz/jwS/7yqcf/qvzgyQ/cCefx7fMn7AhLh+3t0y8LPpVQx+Y+69riJP04nDhdqy5vwTM4fCV1vSLUNlTgEiMwoAadYHx4i29kVVppS7XyDo35X59mUMjKgWcdvQpiQWoryUpcP7xq6lM3hXRvuTG7y4drRI8XJOW7MgAuHAeVcpSH+o2VLXnQyJe10Z/HpUxMTgnKfftYmduF9glj5MeE8/zPCzbfWKJtlQrnz0GTwMpHPdE4e6TMMxioNsFAeTLx5eQB8bfgCw6fZeSayDtD4sFKTtq4i4f+37lxlnC7K/Vw1JtdqSfOpuW6k2B7e+FrLSiWjmxPx57Z8koV3PUao0ZnVb3Fxz/5wtQmSdNfDcENgWSwGdNZoOwZJmkAyM4CWeKUiJnadGsb5sYLooKafRBPhMCmaqUhdqJgfpYqolSVqUQDWjPA4PK7BkESYFqZHpmMR4mPd4LnPfyL9Atyu5GRBU/oKfEAII44ZHJjiIjaSbc3vZO0YLli6HkMsDbi3mVamHxezV/KMnCmJRU3mEwm9fG9MD8M5fG70EqFcvCNwQKyXXs=
          file:
            - CoordinatorKit.framework.zip
          skip_cleanup: true
          overwrite: true
          on:
            repo: bfernandesbfs/CoordinatorKit
            tags: true
